apiVersion: v1
kind: List
items:
  - apiVersion: serving.knative.dev/v1
    kind: Service
    spec:
      template:
        metadata:
          labels:
            name: redhat-airline-airport-api
            appId: 7ipcoeh4nkl6
        spec:
          containers:
            - image: >-
                image-registry.openshift-image-registry.svc:5000/redhat-airline/redhat-airline-airport-api
    metadata:
      name: redhat-airline-airport-api
      namespace: redhat-airline
